import { useState } from 'react';
import { Badge } from '../../components/Badge.jsx';
import { Button } from '../../components/Button.jsx';
import { DataTable } from '../../components/DataTable.jsx';
import { formatMoney, formatOrDash } from '../../lib/format.js';
import { IndicatorSnapshot } from './IndicatorSnapshot.jsx';

const PAGE_SIZE = 50;

const COLUMNS = [
  {
    key: 'status',
    header: 'Status',
    render: (trade) => (
      <Badge tone={trade.status === 'CLOSED' ? 'success' : 'accent'}>{trade.status === 'CLOSED' ? 'Closed' : 'Open'}</Badge>
    ),
  },
  { key: 'entryDate', header: 'Entry date', render: (trade) => trade.entry.date },
  { key: 'exitDate', header: 'Exit date', render: (trade) => formatOrDash(trade.exit?.date) },
  { key: 'quantity', header: 'Quantity', align: 'right', render: (trade) => trade.quantity },
  { key: 'entryPrice', header: 'Entry price', align: 'right', render: (trade) => formatMoney(trade.entry.fillPrice) },
  { key: 'exitPrice', header: 'Exit price', align: 'right', render: (trade) => formatMoney(trade.exit?.fillPrice) },
  { key: 'realizedPnl', header: 'Realized P&L', align: 'right', render: (trade) => formatMoney(trade.realizedPnl) },
  { key: 'unrealizedPnl', header: 'Unrealized P&L', align: 'right', render: (trade) => formatMoney(trade.unrealizedPnl) },
  { key: 'commission', header: 'Commission', align: 'right', render: (trade) => formatMoney(trade.totalCommission) },
  { key: 'slippage', header: 'Slippage', align: 'right', render: (trade) => formatMoney(trade.totalSlippageCost) },
  {
    key: 'entrySignal',
    header: 'Entry signal',
    render: (trade) => <IndicatorSnapshot date={trade.entry.signalDate} close={trade.entry.signalClose} indicators={trade.entry.signalIndicators} />,
  },
  {
    key: 'exitSignal',
    header: 'Exit signal',
    render: (trade) =>
      trade.exit ? (
        <IndicatorSnapshot date={trade.exit.signalDate} close={trade.exit.signalClose} indicators={trade.exit.signalIndicators} />
      ) : (
        '—'
      ),
  },
];

export function TradesTable({ trades }) {
  const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);

  if (trades.length === 0) {
    return <p className="text-sm text-ink-secondary">No trades were generated by this run.</p>;
  }

  const visible = trades.slice(0, visibleCount);
  const remaining = trades.length - visible.length;

  return (
    <div>
      <DataTable columns={COLUMNS} rows={visible} getRowKey={(trade) => trade.entry.orderId} caption="Trades" />
      {remaining > 0 ? (
        <div className="mt-3 flex justify-center">
          <Button variant="secondary" onClick={() => setVisibleCount((count) => count + PAGE_SIZE)}>
            Show more ({remaining} remaining)
          </Button>
        </div>
      ) : null}
    </div>
  );
}
